[package]
name = "soap"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = {version = "^4", features=["derive"]}
rand = "*"
GSL = "*"
ndarray = "*"

[profile.release]
lto = true
codegen-units = 1
strip = true
opt-level = "s"

[profile.dev]
opt-level = "s"
